---
# Tasks for installing Openstack Keystone Packages

- name: Add Keystone Packages
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - python-keystone
    - keystone
    - python-keystoneclient
    - python-openstackclient